# Cấu hình cổng chạy ứng dụng Backend
server.port=8080

# Cấu hình kết nối PostgreSQL - Đã cập nhật database thành gom_db
spring.datasource.url=jdbc:postgresql://localhost:5432/gom_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình tự động tạo/cập nhật cấu trúc bảng dựa trên Entity Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect