# ==============================================================
# CẤU HÌNH PORT & DATABASE ĐỘNG (Bảo mật thông tin Aiven)
# ==============================================================
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gom_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}

# ==============================================================
# CẤU HÌNH HIBERNATE & JPA
# ==============================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true